
<img src="https://i.ibb.co/PQjhtPK/Logo-Datos-Vivos.png" width="400px">

# Curso Introductorio de Python

Publicado por [Escuela de Datos Vivos](https://escueladedatosvivos.ai/) (EDVAI) | [Página oficial del curso](https://escueladedatosvivos.ai/p/curso-gratuito-introduccion-a-python)

Seguinos en las redes para mas contenido:
 [Instagram](https://www.instagram.com/escueladedatosvivos/) | [Linkedin](https://www.linkedin.com/company/escuela-de-datos-vivos/) | [Twitter](https://twitter.com/datos_vivos)

Canal de [YouTube](https://www.youtube.com/c/Escueladedatosvivosai).

<br>


Profesor: [Pablo Casas](https://www.linkedin.com/in/pcasas/).

---

# C.1) Estructuras de control y funciones clásicas

### 1) Nuestro amigo el **IF**

In [1]:
nro_de_cliente=999

if nro_de_cliente==999:
  print('es el cliente 999!!')
else:
  print('cliente no encontrado :(')

es el cliente 999!!


In [2]:
nro_de_cliente=13151

In [3]:
# if anidado
if nro_de_cliente==999:
  print('es el cliente 999!!')
elif nro_de_cliente==111:
  print('es el cliente 111!!')
else:
  print('cliente no encontrado :(')

cliente no encontrado :(


Igual: x1 == x2

Distinto: x1 != x2

Menor a: x1 < x2

Menor o igual a: x1 <= x2

Mayor a: x1 > x2

Mayor o igual x1 >= x2



### 2) *Mientras* vemos el `while`

In [4]:
# imprimir 3 elementos
i=0
while(i<3):
  i=i+1
  print(i)

1
2
3


In [5]:
# bucle infinito
while(1):
  x1=input('¿Nombre? ')

  if x1=='me aburri':
    break

  print('Bienvenido! ' + x1)


¿Nombre? david
Bienvenido! david
¿Nombre? pedro
Bienvenido! pedro
¿Nombre? me aburri


### 3) *Para* que usar while, si hay `for`!

In [6]:
lista=[1,2,3,4]

In [7]:
for i in lista:

  if i == 3:
    break

  print(i)

1
2


¿Cómo usar for sobre pandas data frame?

In [8]:
import pandas as pd

d_star_wars=pd.read_csv(filepath_or_buffer="https://raw.githubusercontent.com/pablo14/datasets/main/star_wars/starwars.csv", sep=',')
d_star_wars.head()


name  height   mass hair_color   skin_color eye_color  \
0  Luke Skywalker   172.0   77.0      blond         fair      blue   
1           C-3PO   167.0   75.0        NaN         gold    yellow   
2           R2-D2    96.0   32.0        NaN  white, blue       red   
3     Darth Vader   202.0  136.0       none        white    yellow   
4     Leia Organa   150.0   49.0      brown        light     brown   

   birth_year     sex     gender homeworld species  
0        19.0    male  masculine  Tatooine   Human  
1       112.0    none  masculine  Tatooine   Droid  
2        33.0    none  masculine     Naboo   Droid  
3        41.9    male  masculine  Tatooine   Human  
4        19.0  female   feminine  Alderaan   Human

In [9]:
# no hacer asi
for row in d_star_wars:
  print(row)



name
height
mass
hair_color
skin_color
eye_color
birth_year
sex
gender
homeworld
species


In [10]:
# Usar iterrows()

for label, row in d_star_wars[:5].iterrows():
  print('El label es: ' + str(label))
  print(row)

El label es: 0
name          Luke Skywalker
height                 172.0
mass                    77.0
hair_color             blond
skin_color              fair
eye_color               blue
birth_year              19.0
sex                     male
gender             masculine
homeworld           Tatooine
species                Human
Name: 0, dtype: object
El label es: 1
name              C-3PO
height            167.0
mass               75.0
hair_color          NaN
skin_color         gold
eye_color        yellow
birth_year        112.0
sex                none
gender        masculine
homeworld      Tatooine
species           Droid
Name: 1, dtype: object
El label es: 2
name                R2-D2
height               96.0
mass                 32.0
hair_color            NaN
skin_color    white, blue
eye_color             red
birth_year           33.0
sex                  none
gender          masculine
homeworld           Naboo
species             Droid
Name: 2, dtype: object
El label es: 3
na

Accediendo a cada valor:

In [11]:
for _, row in d_star_wars[:5].iterrows():
  print('Personaje: ' + row['name'] + ' lugar ' + row['homeworld'])

Personaje: Luke Skywalker lugar Tatooine
Personaje: C-3PO lugar Tatooine
Personaje: R2-D2 lugar Naboo
Personaje: Darth Vader lugar Tatooine
Personaje: Leia Organa lugar Alderaan


### 4) ¿Cómo crear funciones en Python?

In [12]:
def mi_funcion():
  print('hola mundo')

In [13]:
mi_funcion()

hola mundo


¿Cómo crear una función con parámetros?

In [14]:
def sumar(x1, x2):
  return x1+x2

In [15]:
sumar(x1=1, x2=1)

2

¿Cómo explorar el contenido de una función?

In [16]:
%%capture
pip install funpymodeling

In [17]:
from funpymodeling.exploratory import status

In [18]:
??status

In [19]:
status(d_star_wars)

variable  q_nan     p_nan  q_zeros  p_zeros  unique     type
0         name      0  0.000000        0      0.0      87   object
1       height      6  0.068966        0      0.0      45  float64
2         mass     28  0.321839        0      0.0      38  float64
3   hair_color      5  0.057471        0      0.0      12   object
4   skin_color      0  0.000000        0      0.0      31   object
5    eye_color      0  0.000000        0      0.0      15   object
6   birth_year     44  0.505747        0      0.0      36  float64
7          sex      4  0.045977        0      0.0       4   object
8       gender      4  0.045977        0      0.0       2   object
9    homeworld     10  0.114943        0      0.0      48   object
10     species      4  0.045977        0      0.0      37   object

In [20]:
d_star_wars.nunique().values


array([87, 45, 38, 12, 31, 15, 36,  4,  2, 48, 37])

In [21]:
d_star_wars.columns

Index(['name', 'height', 'mass', 'hair_color', 'skin_color', 'eye_color',
       'birth_year', 'sex', 'gender', 'homeworld', 'species'],
      dtype='object')

In [22]:
def status2(data):
  return pd.DataFrame({'variables': data.columns, 'valores_unicos':data.nunique().values})

In [23]:
status2(d_star_wars)

variables  valores_unicos
0         name              87
1       height              45
2         mass              38
3   hair_color              12
4   skin_color              31
5    eye_color              15
6   birth_year              36
7          sex               4
8       gender               2
9    homeworld              48
10     species              37

<br>

---



# C.2.1) ¿Qué es `numpy`?

In [24]:
import numpy as np

In [25]:
arr1=np.array([1,2,3,4,5])

In [26]:
arr1

array([1, 2, 3, 4, 5])

In [27]:
arr1+arr1

array([ 2,  4,  6,  8, 10])

In [28]:
arr1.shape # ranking 1

(5,)

¿Cómo crear un "tabla" en numpy?

Rank 2 array / 2D

In [29]:
arr2=np.array([[1,2,3,4,5], [9,8,7,6,5]])

arr2

array([[1, 2, 3, 4, 5],
       [9, 8, 7, 6, 5]])

In [30]:
arr2.shape

(2, 5)

Rank 3 array / 3D

In [31]:
arr3=np.array([[[1,2,3,4,5], [9,8,7,6,5]]])

In [32]:
arr3.shape

(1, 2, 5)

### C.2.2) ¿Cómo hacer `reshape` en numpy?

In [33]:
arr3=np.array([1,2,3,4,5,6])
print(arr3)
print(arr3.shape)

[1 2 3 4 5 6]
(6,)


In [34]:
arr4=arr3.reshape((2,3))

arr4

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
arr4.shape

(2, 3)

¿Cómo hacer flatten de un numpy array?

In [36]:
arr5=arr4.flatten()
arr5

array([1, 2, 3, 4, 5, 6])

### C.2.3) ¿Cómo hacer slice de numpy?

In [37]:
arr1

array([1, 2, 3, 4, 5])

In [38]:
# 1er elemento
arr1[0]

1

In [39]:
arr1[0:3]

array([1, 2, 3])

### C.2.4) ¿Cómo acceder a arrays n-dimensionales?

In [40]:
arr4

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
arr4[0,:]

array([1, 2, 3])

In [42]:
arr4[1,0]

4

In [43]:
arr4[1,0:2]

array([4, 5])

In [44]:
# acceder a toda la 1er dimensión
arr4[0]

array([1, 2, 3])

Imagen resumen numpy

<img src="https://fgnt.github.io/python_crashkurs_doc/_images/numpy_array_t.png" width="300px">

[Fuente](https://fgnt.github.io/python_crashkurs_doc/include/numpy.html).